---
version: '3.7'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-scram-sha-256}"
      POSTGRES_USER: vapor_username
      POSTGRES_DB: vapor_database
      POSTGRES_PASSWORD: vapor_password
    ports:
      - 5432:5432
